### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by shupcn** [shupcn/shupcn.github.io#1]
- [ ] Screen width (integer)
 - [x] Service worker support
 - [x] Fetch support
 - [ ] CSS flexbox support
 - [ ] Custom elements
